In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/train.txt',sep=';',header = None,names = ['text','emotion'])
df

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]

In [ ]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [ ]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
unique_emo = df['emotion'].unique()
unique_emo

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [ ]:
emotion_no = {}
i=0
for emo in unique_emo:
  emotion_no[emo] = i
  i+=1
emotion_no

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [ ]:
df['emotion'] = df['emotion'].map(emotion_no)
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [ ]:
df['text'] = df['text'].apply(lambda x:x.lower())
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [ ]:
import string

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

df['text'] = df['text'].apply(remove_punctuation)
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [ ]:
def remove_numbers(text):
    return ''.join([i for i in text if not i.isdigit()])

df['text'] = df['text'].apply(remove_numbers)
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [ ]:
import re

def remove_urls(text):
    return re.sub(r'https?:\S+|www\.\S+', '', text)

df['text'] = df['text'].apply(remove_urls)
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [ ]:
def remove_emojis_and_special(text):
    # Remove emojis and non-ASCII characters
    text = text.encode('ascii', 'ignore').decode('ascii')
    # Keep only alphanumeric characters and spaces
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    # Replace multiple spaces with a single space and strip
    return ' '.join(text.split())

df['text'] = df['text'].apply(remove_emojis_and_special)
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('punkit')
nltk.download('stopwords')

[nltk_data] Error loading punkit: Package 'punkit' not found in index
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [ ]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [ ]:
def remove(text):
  words = word_tokenize(text)
  filtered_words = [word for word in words if word.lower() not in stop_words]
  return ' '.join(filtered_words)

In [ ]:
import nltk
nltk.download('punkt_tab')

# Re-apply the stopword removal function
df['text'] = df['text'].apply(remove)
df

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [ ]:
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [ ]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [ ]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [ ]:
X_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
bow_vectorizer = CountVectorizer()
tfidf_vectorizer = TfidfVectorizer()

In [ ]:
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [ ]:
X_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 116049 stored elements and shape (12800, 13359)>

In [ ]:
X_train_tfidf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 116049 stored elements and shape (12800, 13359)>

In [ ]:
from sklearn.naive_bayes import MultinomialNB #specifically for word classification involt=ving frequency
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)

MultinomialNB()

In [ ]:
nb_bow_pred = nb_model.predict(X_test_bow)
nb_bow_accuracy = accuracy_score(y_test, nb_bow_pred)

In [ ]:
print("Naive Bayes with Bag-of-Words Accuracy:", nb_bow_accuracy)

Naive Bayes with Bag-of-Words Accuracy: 0.7678125

In [ ]:
print(classification_report(y_test, nb_bow_pred))

              precision    recall  f1-score   support

           0       0.75      0.95      0.84       946
           1       0.89      0.63      0.74       427
           2       0.93      0.26      0.41       296
           3       1.00      0.05      0.10       113
           4       0.85      0.57      0.68       397
           5       0.73      0.96      0.83      1021

    accuracy                           0.77      3200
   macro avg       0.86      0.57      0.60      3200
weighted avg       0.80      0.77      0.74      3200

In [ ]:
nb_model_tfidf = MultinomialNB()
nb_model_tfidf.fit(X_train_tfidf, y_train)

MultinomialNB()

In [ ]:
pred_tfidf = nb_model_tfidf.predict(X_test_tfidf)
accuracy_tfidf = accuracy_score(y_test, pred_tfidf)

In [ ]:
print("Naive Bayes with TF-IDF Accuracy:", accuracy_tfidf)
print(classification_report(y_test, pred_tfidf))

Naive Bayes with TF-IDF Accuracy: 0.6609375
              precision    recall  f1-score   support

           0       0.70      0.93      0.80       946
           1       0.93      0.29      0.44       427
           2       1.00      0.03      0.06       296
           3       1.00      0.01      0.02       113
           4       0.92      0.22      0.36       397
           5       0.60      0.99      0.74      1021

    accuracy                           0.66      3200
   macro avg       0.86      0.41      0.40      3200
weighted avg       0.76      0.66      0.58      3200

In [ ]:
lg_model = LogisticRegression(max_iter = 1000)
lg_model.fit(X_train_bow, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
pred_tfidf_lg = lg_model.predict(X_test_tfidf)
accuracy_tfidf_lg = accuracy_score(y_test, pred_tfidf_lg)

In [ ]:
print("Logistic Regression with TF-IDF Accuracy:", accuracy_tfidf_lg)
print(classification_report(y_test, pred_tfidf_lg))
#

Logistic Regression with TF-IDF Accuracy: 0.825625
              precision    recall  f1-score   support

           0       0.88      0.93      0.91       946
           1       0.85      0.89      0.87       427
           2       0.99      0.22      0.36       296
           3       0.94      0.14      0.25       113
           4       0.90      0.73      0.80       397
           5       0.75      0.98      0.85      1021

    accuracy                           0.83      3200
   macro avg       0.88      0.65      0.67      3200
weighted avg       0.85      0.83      0.80      3200

In [60]:
# Initialize Logistic Regression with the best parameters
best_lr_model = LogisticRegression(C=10.0, max_iter=1000, random_state=42)

# Fit the model on the TF-IDF training data
best_lr_model.fit(X_train_tfidf, y_train)

# Predict on the TF-IDF test data
y_pred_lr = best_lr_model.predict(X_test_tfidf)

# Evaluate accuracy and generate classification report
lr_accuracy = accuracy_score(y_test, y_pred_lr)
print(f"Optimized Logistic Regression Accuracy: {lr_accuracy:.4f}\n")
print("Classification Report:")
print(classification_report(y_test, y_pred_lr, target_names=list(emotion_no.keys())))

Optimized Logistic Regression Accuracy: 0.8816

Classification Report:
              precision    recall  f1-score   support

     sadness       0.92      0.93      0.92       946
       anger       0.89      0.85      0.87       427
        love       0.85      0.71      0.77       296
    surprise       0.85      0.63      0.72       113
        fear       0.86      0.82      0.84       397
         joy       0.87      0.95      0.91      1021

    accuracy                           0.88      3200
   macro avg       0.87      0.82      0.84      3200
weighted avg       0.88      0.88      0.88      3200

In [61]:
import pickle

# Save the trained Logistic Regression model
with open('best_lr_model.pkl', 'wb') as model_file:
    pickle.dump(best_lr_model, model_file)

# Save the TF-IDF vectorizer
with open('tfidf_vectorizer.pkl', 'wb') as vec_file:
    pickle.dump(tfidf_vectorizer, vec_file)

# Save the emotion mapping dictionary
with open('emotion_mapping.pkl', 'wb') as mapping_file:
    pickle.dump(emotion_no, mapping_file)

print("Pickle files saved successfully:")
print("- best_lr_model.pkl")
print("- tfidf_vectorizer.pkl")
print("- emotion_mapping.pkl")

Pickle files saved successfully:
- best_lr_model.pkl
- tfidf_vectorizer.pkl
- emotion_mapping.pkl

In [63]:
%%writefile app.py
import streamlit as st
import pickle
import re
import string

# Set Page configuration
st.set_page_config(page_title="Emotion Classifier", page_icon="🎭", layout="centered")

# Load Pickle Artifacts
@st.cache_resource
def load_artifacts():
    with open('best_lr_model.pkl', 'rb') as model_file:
        model = pickle.load(model_file)
    with open('tfidf_vectorizer.pkl', 'rb') as vec_file:
        vectorizer = pickle.load(vec_file)
    with open('emotion_mapping.pkl', 'rb') as mapping_file:
        mapping = pickle.load(mapping_file)

    # Reverse mapping to get emotion name from predicted label index
    reverse_mapping = {v: k for k, v in mapping.items()}
    return model, vectorizer, reverse_mapping

try:
    model, vectorizer, reverse_mapping = load_artifacts()
except Exception as e:
    st.error(f"Error loading artifacts: {e}")

# Preprocessing Functions
def preprocess_text(text):
    # 1. Lowercase
    text = text.lower()
    # 2. Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # 3. Remove numbers
    text = ''.join([i for i in text if not i.isdigit()])
    # 4. Remove URLs
    text = re.sub(r'https?:\S+|www\.\S+', '', text)
    # 5. Remove emojis and non-ASCII characters
    text = text.encode('ascii', 'ignore').decode('ascii')
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = ' '.join(text.split())
    return text

# Design the UI/UX
st.title("🎭 Emotion Classifier App")
st.write("Enter a text passage below to predict the underlying emotion.")

user_input = st.text_area("Your Text:", height=150, placeholder="Type how you feel today...")

# Emotion representation mapping
emotion_emojis = {
    'sadness': "😢 Sadness",
    'anger': "😡 Anger",
    'love': "❤️ Love",
    'surprise': "😲 Surprise",
    'fear': "😨 Fear",
    'joy': "😊 Joy"
}

if st.button("Classify Emotion", use_container_width=True):
    if user_input.strip() == "":
        st.warning("Please enter some text before processing.")
    else:
        # Preprocess input text
        clean_text = preprocess_text(user_input)

        # Vectorize text
        vectorized_text = vectorizer.transform([clean_text])

        # Predict class & probabilities
        prediction = model.predict(vectorized_text)[0]
        probabilities = model.predict_proba(vectorized_text)[0]

        predicted_emotion = reverse_mapping[prediction]
        emoji_name = emotion_emojis.get(predicted_emotion, predicted_emotion.capitalize())

        # Display results
        st.success(f"Predicted Emotion: **{emoji_name}**")

        # Display class probabilities visualizer
        st.write("### Confidence Levels:")
        for idx, prob in enumerate(probabilities):
            class_name = reverse_mapping[idx]
            emoji_label = emotion_emojis.get(class_name, class_name.capitalize())
            st.write(f"{emoji_label}: {prob:.2%}")
            st.progress(float(prob))

Overwriting app.py